development: &default
  enabled: true
  minimize: false
  source: 'src/assets/styles'
  target: 'dist/styles'
  selector: '**/*.sass'
  source_maps: './maps'

test:
  <<: *default

production:
  <<: *default
  minimize: true
  source_maps:
